import React from 'react';
import axios from 'axios';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import Card from '../src/components/card/card';
import { ComputerBasicInfo } from '../src/types/data';

import styles from '../src/styles/Home.module.css';
interface HomeProps {
  computers: ComputerBasicInfo[];
}

const Home: NextPage<HomeProps> = (props) => {
  const { computers } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Sklep komputerowy</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap'
        />
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/icon?family=Material+Icons'
        />
      </Head>

      <main style={{ display: 'flex' }}>
        {computers.map((item) => (
          <Card {...item} key={item.id} />
        ))}
      </main>
    </div>
  );
};

export async function getStaticProps() {
  const response = await axios.get('http://localhost:3000/api/computer/', {
    headers: { 'Content-Type': 'application/json' },
  });

  const computers: ComputerBasicInfo[] = await response.data;

  return {
    props: { computers: computers },
  };
}

export default Home;
